<!DOCTYPE html>
<html>
<head>
    <title>Low Stock Item Report</title>
    <style>
        /* General styling */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .header{
            text-align: center;
        }
        .content {
            padding-bottom: 50px; /* Prevents content from overlapping footer */
        }
        .footer {
            position: fixed;
            bottom: 0;
            right: 0;
            margin: 10px;
            text-align: right;
            font-size: 0.8em;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>

    <!-- Header Section -->
    <div class="header">
        <h2>Divine Word College of Calapan</h2>
        <p>Gov. Infantado St. Calapan City, Oriental Mindoro, Philippines</p>
        <h3>DWCC STORE: Sales and Inventory</h3>
    </div>

    <h3 style="text-align: center">Low Stock Item Report</h3>
    <p><strong>Date Range:</strong> {{ $startDate ?? 'All Date' }} to {{ $endDate ?? 'All Date' }}</p>
    <!-- Display the selected filters -->
    <p><strong>Item Name:</strong> {{ $itemName ?? 'All Items' }}</p>
    <p><strong>Category:</strong> {{ $category ?? 'All Categories' }}</p>


    <!-- Table Section -->
    <table>
        <thead>
            <tr>
                <th>Barcode Number</th>
                <th>Item Name</th>
                <th>Category</th>
                <th>Stock Available</th>
                <th>Date Encoded</th>
            </tr>
        </thead>
        <tbody>
            @foreach($lowStockItems as $item)
                <tr>
                    <td>{{ $item->barcode }}</td>
                    <td>{{ $item->item_name }}</td>
                    <td>{{ $item->category->category_name }}</td>
                    <td>{{ $item->qtyInStock }}</td>
                    <td>{{ $item->created_at->format('m-d-Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- Footer Section -->
    <div class="footer">
        <p>Generated by: {{ $userFullName }}</p>
        <p>Generation Date: {{ \Carbon\Carbon::now()->format('m-d-Y h:i:s a') }}</p>
    </div>

</body>
</html>
