<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .header, .footer {
            width: 100%;
            text-align: center;
        }
        .header {
            border-bottom: 1px solid #000;
            padding: 5px 0; /* Reduced padding */
        }
        .header h2, .header h3, .header p {
            margin: 2px 0; /* Reduced margin for tighter spacing */
        }
        .header h2 {
            font-weight: bold;
        }
        .header h3 {
            font-weight: bold;
            margin-top: 3px;
        }
        .table-container {
            padding-top: 30px; /* Reduced padding to bring table closer */
            margin-bottom: 20px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 0;
        }
        .table th, .table td {
            border: 1px solid #000;
            padding: 5px;
            text-align: left;
        }
        .table th {
            background-color: #66C571;
        }
        .category-header {
            background-color: #66C571;
            font-weight: bold;
            padding: 8px 5px;
            margin-top: 10px; /* Adjusted for less vertical space */
            margin-bottom: 0;
        }
        .footer {
            position: fixed;
            bottom: 0;
            border-top: 1px solid #000;
            padding-top: 10px;
            width: 100%;
        }
        .footer-content {
            display: flex;
            justify-content: space-between;
            font-size: 0.9rem;
            padding: 0 20px;
        }
        
        @media print {
            .header {
                display: block;
                position: fixed;
                top: 0;
                width: 100%;
            }
            .header + .table-container {
                padding-top: 40px; /* Adjusted for header height */
            }
        }
        
        /* Column widths */
        .table th:nth-child(1), .table td:nth-child(1) { width: 30%; }
        .table th:nth-child(2), .table td:nth-child(2) { width: 10%; }
        .table th:nth-child(3), .table td:nth-child(3) { width: 10%; }
        .table th:nth-child(4), .table td:nth-child(4) { width: 15%; }
        .table th:nth-child(5), .table td:nth-child(5) { width: 15%; }
        .table th:nth-child(6), .table td:nth-child(6) { width: 10%; }
        .table th:nth-child(7), .table td:nth-child(7) { width: 10%; }
    </style>
</head>
<body>

<div class="header">
    <h2>DIVINE WORD COLLEGE OF CALAPAN</h2>
    <p>Calapan City, Oriental Mindoro</p>
    <h3>COLLEGE BOOKSTORE INVENTORY</h3>
    <p>As of {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
</div>

<div class="table-container">
    @foreach ($items as $category => $categoryItems)
        <div class="category-header">Category: {{ $category }}</div>
        <table class="table">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Quantity</th>
                    <th>Unit</th>
                    <th>Base Price</th>
                    <th>Selling Price</th>
                    <th>Total Base Price</th>
                    <th>Total Selling Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categoryItems as $item)
                    <tr>
                        <td>{{ $item->item_name }}</td>
                        <td>{{ $item->qtyInStock }}</td>
                        <td>{{ $item->unit_of_measurement }}</td>
                        <td>{{ number_format($item->base_price, 2) }}</td>
                        <td>{{ number_format($item->selling_price, 2) }}</td>
                        <td>{{ number_format($item->qtyInStock * $item->base_price, 2) }}</td>
                        <td>{{ number_format($item->qtyInStock * $item->selling_price, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endforeach
</div>

<div class="footer">
    <div class="footer-content">
        <div>Generated by: {{ $userFullName }}</div>
        <div>Generation Date:{{ \Carbon\Carbon::now()->format('m-d-Y h:i:s a') }}</div>
    </div>
</div>

</body>
</html>
