<!DOCTYPE html>
<html>
<head>
    <title>Sales Report</title>
    <style>
        /* General styling */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .header {
            text-align: center;
        }
        .content {
            margin: 20px;
            padding-bottom: 50px; /* Prevents content from overlapping footer */
        }
        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            text-align: right;
            font-size: 0.8em;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed; /* Ensures consistent column widths */
            word-wrap: break-word; /* Prevents overflow by wrapping text */
            font-size: 10px; /* Small font size for compact layout */
        }
        th, td {
            border: 1px solid #000;
            padding: 5px; /* Smaller padding for compact rows */
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .total {
            text-align: right;
            margin-top: 10px;
            font-size: 0.9em;
            font-weight: bold;
        }
        @page {
            margin: 20px;
        }
        thead {
            display: table-header-group; /* Ensures headers repeat on each new page */
        }
        tfoot {
            display: table-footer-group; /* Ensures footers repeat on each new page */
        }
        tr {
            page-break-inside: avoid; /* Prevents row splitting across pages */
        }
    </style>
</head>
<body>

    <!-- Header Section -->
    <div class="header">
        <h2>Divine Word College of Calapan</h2>
        <p>Gov. Infantado St. Calapan City, Oriental Mindoro, Philippines</p>
        <h3>DWCC STORE: Sales and Inventory</h3>
    </div>

    <!-- Report Title -->
    <h3 style="text-align: center">Sales Report</h3>
    <p><strong>Date Range:</strong> {{ $startDate ?? 'All Dates' }} to {{ $endDate ?? 'All Dates' }}</p>
    <p><strong>Payment Method:</strong> {{ $paymentMethod ?? 'All Methods' }}</p>
    <p><strong>Category:</strong> {{ $categoryName ?? 'All Categories' }}</p>

    <!-- Table Section -->
    <div class="content">
        <table>
            <thead>
                <tr>
                    <th style="width: 10%;">Date/Time</th>
                    <th style="width: 10%;">Trans. #</th>
                    <th style="width: 20%;">Item Name</th>
                    <th style="width: 15%;">Category</th>
                    <th style="width: 10%;">Quantity</th>
                    <th style="width: 10%;">Price</th>
                    <th style="width: 10%;">Total</th>
                    <th style="width: 10%;">Payment Method</th>
                    <th style="width: 15%;">Cashier Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transactions as $transaction)
                    @foreach ($transaction->items as $item)
                        <tr>
                            <td>{{ $transaction->created_at->format('Y-m-d H:i:s') }}</td>
                            <td>{{ $transaction->transaction_no }}</td>
                            <td>{{ $item->item_name }}</td>
                            <td>{{ $item->item->category->category_name ?? 'N/A' }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td style="text-align: right;">{{ number_format($item->price, 2) }}</td>
                            <td style="text-align: right;">{{ number_format($item->total, 2) }}</td>
                            <td>{{ ucfirst($transaction->payment_method) }}</td>
                            <td>{{ $transaction->user->full_name ?? 'N/A' }}</td>
                        </tr>
                    @endforeach
                @endforeach
            </tbody>
        </table>

        <!-- Total Sales -->
        <div class="total">
            <p>Total Sales: {{ number_format($totalSales, 2) }}</p>
        </div>
    </div>

    <!-- Footer Section -->
    <div class="footer">
        <p>Generated by: {{ $userFullName }}</p>
        <p>Generation Date: {{ \Carbon\Carbon::now()->format('m-d-Y h:i:s a') }}</p>
    </div>

</body>
</html>
