<!DOCTYPE html>
<html>
<head>
    <title>Damage Item Report</title>
    <style>
        /* General styling */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        .header{
            text-align: center;
        }
        .content {
            padding-bottom: 50px; /* Prevents content from overlapping footer */
        }
        .footer {
            position: fixed;
            bottom: 0;
            right: 0;
            margin: 10px;
            text-align: right;
            font-size: 0.8em;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>

    <!-- Header Section -->
    <div class="header">
        <p><strong>Divine Word College of Calapan</strong></p>
        <p>Gov. Infantado St. Calapan City, Oriental Mindoro, Philippines</p>
        <p><strong>DWCC STORE: Sales and Inventory</strong></p>
    </div>

    <h3 style="text-align: center">Void Logs Item Report</h3>
    <p><strong>Date Range:</strong> {{ $startDate ?? 'All Date' }} to {{ $endDate ?? 'All Date' }}</p>
    <!-- Display the selected filters -->
    <p><strong>Item Name:</strong> {{ $itemName ?? 'All Items' }}</p>
    <p><strong>Category:</strong> {{ $category ?? 'All Categories' }}</p>


    <!-- Table Section -->
    <table>
            <thead>
                <tr>
                    <th>Date/Time</th>
                    <th>Item Name</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Cashier Name</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($voidRecords as $void)
                <tr>
                    <td>{{ $void->voided_at ? $void->voided_at->format('m-d-Y h:i:s a') : 'N/A' }}</td>
                    <td>{{ $void->item_name ?? 'N/A' }}</td>
                    <td>{{ $void->items->category->category_name ?? 'N/A' }}</td>
                    <td>{{ number_format($void->price, 2) }}</td>
                    <td>{{ $void->voided_by }}</td>
                </tr>
            @endforeach
            </tbody>
    </table>

    <!-- Footer Section -->
    <div class="footer">
        <p>Generated by: {{ $userFullName }}</p>
        <p>Generation Date: {{ \Carbon\Carbon::now()->format('m-d-Y h:i:s a') }}</p>
    </div>

</body>
</html>